name: Deploy SRG AI Frontend

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ vars.PROJECT_NAME }}

jobs:
  build-and-deploy:
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        # This step is crucial for multi-platform builds
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          # Using GITHUB_TOKEN is fine, but a PAT with write:packages is also a secure option
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-platform Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Step 1: Login to GHCR
            echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
            
            # Step 2: Pull the latest image
            docker pull ${{ env.IMAGE_NAME }}:latest
            
            # Step 3: Create or update the docker-compose.yml file with corrected syntax
            cat << 'EOF' > ~/docker-compose.yml
            version: '3.8'
            services:
              frontend:
                image: ${{ env.IMAGE_NAME }}:latest
                container_name: ${{ vars.PROJECT_NAME }}
                restart: unless-stopped
                networks: 
                  - npm
                volumes:
                  - 'srg-ai-front:/app/data'
        
            networks:
              npm:
                external: true

            volumes:
              srg-ai-front:
            EOF
            
            # Step 4: Stop the old container and start the new one
            docker compose -f ~/docker-compose.yml up -d --force-recreate
            
            # Step 5: Clean up old, unused Docker images
            docker image prune -f